image: node:latest

stages:
    - build
    - test
    - debug
    
cache:
    paths:
        - node_modules/
        
install_dependencies:
    stage: build
    script:
        - npm install
    artifacts:
        paths:
            - node_modules/
testing:
    stage: test
    script: npm test

running:
    stage: debug
    script:
        - DEBUG=Index node server.js